# HR Optimization with Python-MIP

This notebook attempts to reproduce the results published in the paper https://www.researchgate.net/publication/343517283_Mathematical_Model_and_Its_Solution_of_the_Optimization_Problem_in_Human_Resource_Management_of_Chinese_State-Owned_Enterprises_and_Institutions.

In [ ]:
try:
    import mip
except:
    !pip install mip==1.16rc0
    import mip

import numpy as np
import pandas as pd

In [ ]:
# Salaries.
S = [
    750000,
    600000,
    510000,
    450000,
    520000,
    520000,
    510000,
    510000,
    510000,
    510000,
    510000,
    330000,
    315000,
    330000,
    330000,
    330000,
    330000,
    330000,
    270000,
    240000,
    180000,
]


m = mip.Model("HR Allocation")

# Decision variables are positive integers.
x = [m.add_var(var_type=mip.INTEGER, lb=1) for i in range(len(S))]

# Objective to minimize.
m.objective = mip.minimize(mip.xsum(S[i]*x[i] for i in range(len(S))))

# Constraints.
m += x[2] + x[8] + x[16] == 7
m += x[12] + x[19] == 7
m += x[11] + x[18] == 2
m += x[10] + x[3] == 4
m += x[20] == 3
m += mip.xsum(x[i] for i in range(0, 4)) <= 70
m += mip.xsum(x[i] for i in range(4, 13)) <= 100
m += mip.xsum(x[i] for i in range(0, 4)) <= 0.1*(mip.xsum(x[i] for i in range(21)))
m += 60000*mip.xsum(x[i] for i in range(13, 21)) <= 3600000
m += mip.xsum(S[i]*x[i] for i in range(13, 21)) <= 6195000
m += mip.xsum(S[i]*x[i] for i in range(4, 13)) <= 12270000
m += mip.xsum(S[i] * x[i] for i in range(0, 4)) <= 3150000
m += mip.xsum(x[i] for i in range(13, 21)) <= 50
m += 0.5 * mip.xsum(x[i] for i in range(21)) <= mip.xsum(x[i] for i in range(4, 13))
m += 0.4 * mip.xsum(x[i] for i in range(21)) <= mip.xsum(x[i] for i in range(13, 21))

m.optimize()

In [ ]:
d = {"Variable": [], "Value": []}
for i in range(len(x)):
    d["Variable"].append("x_{}".format(i+1))
    d["Value"].append(int(x[i].x))

d["Variable"].append("Objective")
d["Value"].append(int(m.objective.x))

df = pd.DataFrame(d)

display(df.loc[0:int(len(df) / 2)].T)
display(df.loc[int(len(df) / 2)+1:].T)

           0    1    2    3    4    5    6    7    8     9     10    11
Variable  x_1  x_2  x_3  x_4  x_5  x_6  x_7  x_8  x_9  x_10  x_11  x_12
Value       1    1    1    1    1    1    5    1    1     1     3     1

            12    13    14    15    16    17    18    19    20         21
Variable  x_13  x_14  x_15  x_16  x_17  x_18  x_19  x_20  x_21  Objective
Value        6     3     1     1     5     1     1     1     3   15860000